name: WakaNew

on:
  schedule:
    - cron: '0 */12 * * *' # 每12小时更新一次
  workflow_dispatch:      # 允许手动触发

jobs:
  update-readme:
    name: Update GitHub Profile with WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: WakaTime Metrics
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "true"                     # 显示更新时间
          SHOW_TOTAL: "true"                            # 显示总编码时间
          SHOW_LANGUAGE: "true"                         # 显示语言统计
          SHOW_OS: "true"                               # 显示操作系统统计
          SHOW_PROJECTS: "true"                         # 显示项目统计
          SHOW_TIMEZONE: "true"                         # 显示时区
          SHOW_COMMIT: "true"                           # 显示提交次数
